### ISSUE TITLE
[META] Plugin Wishlist

### ISSUE THREAD

**Issue by FWirtz** [schul-cloud/edtrio#41]
Collection of plugins to be implemented:
- [ ] LaTeX
- [ ] Audio
- [ ] Syntax Highlight
- [ ] Vokabeltest
- [ ] Chemie: Formeleditor
- [ ] TextInput (Question/Answer)
- [ ] MathQuiz
- [ ] Etherpad
- [ ] Nexboard
- [ ] File Viewer (PDF/Word/etc.)
- [ ] File Download / File Preview
- [ ] ...

**Comment by janrenz** [comment]
what about homework in the scope of Schule-Cloud? lets discuss this offline..
