### ISSUE TITLE
Roadmap for edtrio@next

### ISSUE THREAD

**Issue by FWirtz** [schul-cloud/edtrio#66]
Moved to: https://paper.dropbox.com/doc/Edtr.ionext-Roadmap--AJl_q1fXfXryIajSNqLixNlBAQ-Fb30qtjeRjsZqxmlChLJv

---
<details>
  <summary>Initial steps</summary>
  
- [x] Finish reading Slate docs
- [x] Add [JSON viewer](https://github.com/mac-s-g/react-json-view) option to dev mode that displays the document json to the right (toggleable) (see 4d855392ef1fa5418ed199cb4ea188b9a8fe1349)
- [X] Get rid of `create-react-app` boilerplate (see 2e65366236019dfe5845de424edf67cb568168bc)
- [x] Try to create a button that toggles some Mark or node (see acf3dc8ea1278062deae459440013833cfcc54e5)
- [x] Figure out how to `detect link paste -> insert custom node` [pbbly this helps](https://ianstormtaylor.github.io/slate-plugins/#/slate-drop-or-paste-images)
- [X] Create first plugin that turns a pasted link into an actual link (see bc7a8b6dc63199243fd2e985da34e8f39e0ef16d)
- [x] create further roadmap (see [below](https://github.com/schul-cloud/edtrio/issues/66#issuecomment-410807947))
</details>

**Comment by FWirtz** [comment]
also, whats this: https://github.com/jigish/slate/wiki/Keystrokes ?

**Comment by FWirtz** [comment]
## Further ToDos
- [ ] more core components:
    - [ ] all from `Edtrio@master`
    - [ ] ...whatever else we need?
- [ ] create a custom schema - pbbly something that enforces:
    - [ ] headline
    - [ ] no more inlines/marks/nodes inside `CodeBlock`s
    - [ ] ...
- [ ] some decent basic CSS
    - [ ] not ugly font
    - [ ] define some color schema (inspired by SC pbbly)
- [ ] better docs (maybe even use [mdx](https://github.com/mdx-js/mdx) would f*in love to use that!) so people can get started easily
- [ ] some routine to auto-deploy somewhere (AWS S3 bucket atm?)
- [ ] ... what else? ♨️ ☕️
